run_stats/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # Home page
    path('', views.index, name="index"),

    # Run page
    path('runs', views.runs, name="runs"),

    # Detail page for a single run
    path('runs/<int:run_id>', views.run, name="run"),

    # Page to add a new Run
    path('runs/new_run', views.new_run, name="new_run"),

    # Page to edit a Run
    path('runs/edit_run/<int:run_id>', views.edit_run, name="edit_run"),

    # Page to delete Run
    path('runs/<int:run_id>/delete_run', views.delete_run, name="delete_run"),
    
    # Page to add Splits
    path('runs/<int:run_id>/add_splits', views.add_splits, name="add_splits"),

    # Page to view schedules
    path('schedules', views.get_schedules, name="schedules"),

    # Page to view schedule
    path('schedule/<int:schedule_id>', views.get_schedule, name="get_schedule"),
]

stat_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('run_stats.urls', 'run_stats'), namespace="run_stats")),
    path('users/', include(('users.urls', 'users'), namespace="users")),
]

users/urls.py
"""Defines url patterns for users."""

from django.contrib.auth.views import LoginView
from django.urls import path

from . import views

urlpatterns = [
    # Login page
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    # Logout page
    path('users/', views.logout_view, name='logout'),
    # Registration form
    path('register', views.register, name='register')
]

run_stats/models.py
from django.contrib.auth.models import User
from django.db import models


class Schedule(models.Model):
    """A schedule to track your progress over time"""
    created_date = models.DateField(auto_now_add=True)
    start_date = models.DateField()
    end_date = models.DateField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Return a string representation of the model."""
        return str(self.start_date) + " to " + str(self.end_date)


class Run(models.Model):
    """A run the user wants to track."""
    date = models.DateField()
    time = models.TimeField()
    distance = models.DecimalField(max_digits=4, decimal_places=2)
    average_speed = models.DecimalField(max_digits=3, decimal_places=1)
    calories_burned = models.IntegerField()
    steps = models.IntegerField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    schedule = models.ForeignKey(Schedule, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        """Return a string representation of the model."""
        return str(self.distance) + " miles - " + str(self.time)[3:] + " minutes"


class Split(models.Model):
    """A time split for each mile on the run."""
    created_date = models.DateField(auto_now_add=True)
    time = models.TimeField()
    length = models.DecimalField(max_digits=3, decimal_places=2)
    run = models.ForeignKey(Run, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Return a string representation of the model."""
        return str(self.time)[3:]

users/models.py
from django.db import models

# Create your models here.

run_stats/forms.py
from django import forms

from .models import Run, Split


class DateInput(forms.DateInput):
    input_type = 'date'


class RunForm(forms.ModelForm):
    class Meta:
        model = Run
        fields = ['date', 'time', 'distance', 'average_speed', 'calories_burned', 'steps' ]
        widgets = {
            'date': DateInput()
        }


class SplitForm(forms.ModelForm):
    class Meta:
        model = Split
        fields = ['time', 'length', 'run']
        # labels = {'time': '00:'}
        widgets = {
            'date': DateInput(),
            'time': forms.TimeInput(format='%M:%S')
        }

    def __str__(self):
        return str(self["time"])

run_stats/views.py
from django.contrib.auth.decorators import login_required
from django.forms import modelformset_factory
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render
from django.urls import reverse

from .forms import RunForm, SplitForm
from .models import Run, Split, Schedule


def index(request):
    """The home page for stat-tracker."""
    return render(request, "run_stats/index.html")


@login_required
def runs(request):
    """Return all runs related to a user."""
    runs = Run.objects.filter(owner=request.user).order_by('-date')
    context = {'runs': runs}
    return render(request, "run_stats/runs.html", context)


@login_required
def run(request, run_id):
    """Show a single run and its splits."""
    run = Run.objects.get(id=run_id)
    validate_user(request, run)
    splits = run.split_set.order_by('-created_date')
    context = {'run': run, 'splits': splits}
    return render(request, 'run_stats/run.html', context)


@login_required
def new_run(request):
    """Add a new run."""
    if request.method != 'POST':
        form = RunForm(initial={'time': '00:'})
    else:
        form = RunForm(request.POST)
        if form.is_valid():
            new_run = form.save(commit=False)
            new_run.owner = request.user
            new_run.save()
            return HttpResponseRedirect(reverse('run_stats:runs'))

    context = {'form': form}
    return render(request, 'run_stats/new_run.html', context)


@login_required
def edit_run(request, run_id):
    """Edit an existing run."""
    run = Run.objects.get(id=run_id)
    validate_user(request, run)
    if request.method != 'POST':
        form = RunForm(instance=run)
    else:
        form = RunForm(instance=run, data=request.POST)
        if form.is_valid:
            form.save()
            return HttpResponseRedirect(reverse('run_stats:runs'))

    context = {'form': form, 'run': run}
    return render(request, 'run_stats/edit_run.html', context)


@login_required
def delete_run(request, run_id):
    """Delete an existing run."""
    run = Run.objects.filter(id=run_id)
    validate_user(request, run)
    if run.delete():
        return HttpResponseRedirect(reverse('run_stats:runs'))


@login_required
def add_splits(request, run_id):
    """Add splits to an existing run."""
    run = Run.objects.get(id=run_id)
    validate_user(request, run)
    print('run_id: ', run_id)
    print('run.split_set: ', run.split_set)
    splits = run.split_set.order_by('-created_date')
    SplitFormsetFactory = modelformset_factory(Split, fields=('time', 'length', 'run'),
                                               form=SplitForm, can_delete=True, can_order=True)
    if request.method != 'POST':
        formset = SplitFormsetFactory(queryset=splits)
    else:
        formset = SplitFormsetFactory(request.POST)
        if formset.is_valid():
            for form in formset:
                if form.is_valid() and form.has_changed():
                    split = form.save(commit=False)
                    split.owner = request.user
                    split.save()
        return HttpResponseRedirect(reverse('run_stats:run', kwargs={'run_id': run.id}))

    context = {
        'formset': formset,
        'splits': splits,
        'run': run
    }

    return render(request, 'run_stats/add_splits.html', context)


@login_required
def get_schedules(request):
    """Get a user's schedules."""
    schedules = Schedule.objects.filter(owner=request.user).order_by('-start_date')
    print(schedules)
    context = {
        'schedules': schedules
    }
    return render(request, 'schedule/schedules.html', context)


@login_required
def get_schedule(request, schedule_id):
    context = {}
    return render(request, 'schedule/schedule.html', context)


def validate_user(request, run):
    if run.owner != request.user:
        raise Http404

users/views.py
from django.contrib.auth import logout, login
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse


def logout_view(request):
    """Log the user out."""
    logout(request)
    return HttpResponseRedirect(reverse('run_stats:index'))


def register(request):
    """Register a new user."""
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return HttpResponseRedirect(reverse('run_stats:index'))

    context = {'form': form}

    return render(request, 'users/register.html', context)

run_stats/templates/run_stats/add_splits.html
{% extends "run_stats/run.html" %}
{% load bootstrap5 %}
{% block content %}

    <p>Splits:</p>

    <div class="form-container">
        <form class="split-form" name="split_form" enctype="multipart/form-data"
              action="{% url 'run_stats:add_splits' run.id %}" method="post">
            {% csrf_token %}
            {{ formset.management_form }}
            {% if formset %}
                <div id="split-form-list" class="split-form-list form-group">
                    {% for form in formset.forms %}

                        <div class="split-form-container">

                            {{ form.non_field_errors }}

                            {% for hidden_field in form.hidden_fields %}
                                {{ hidden_field.errors }}
                                {{ hidden_field }}
                            {% endfor %}

                            {% for field in form %}
                                {% if field.errors %}
                                    <ul>
                                        {% for error in field.errors %}
                                            <li>{{ error }}</li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                                {% bootstrap_field field %}
                                {% if field.help_text %}
                                    <br/>{{ field.help_text }}
                                {% endif %}
                            {% endfor %}

                        </div>
                    {% endfor %}
                </div>
            {% endif %}

            <div style="text-align: center">
                <button class="btn btn-primary" type="button" id="save-btn" onclick="submitForms(event)">save</button>
                <button class="btn btn-secondary" id="add-split" type="button" onclick="addSplit(event)">Add split
                </button>
            </div>
        </form>
    </div>


    <div class="hidden" id="empty-form">
        {% if formset %}
            {{ formset.empty_form }}
        {% endif %}
    </div>

{% endblock content %}

run_stats/templates/run_stats/base.html
<!DOCTYPE html>
<html lang="en">
{% include 'run_stats/head.html' %}
<body>
<div class="page-header">
    {% include 'run_stats/nav.html' %}
    {% block header %}{% endblock header %}
</div>
<div class="body">
    {% block content %}{% endblock content %}
</div>
</body>
</html>

run_stats/templates/run_stats/edit_run.html
{% extends "run_stats/base.html" %}
{% load bootstrap5 %}
{% block content %}

    <h1 class="header">Edit run:</h1>

    <form class="run-form" action="{% url 'run_stats:edit_run' run.id %}"
          method="post">
        {% csrf_token %}
        <div class="card border">
            {% bootstrap_form form %}
        </div>
        <div style="text-align: center">
            {% buttons submit='save' %}{% endbuttons %}
        </div>
    </form>
{% endblock content %}

run_stats/templates/run_stats/head.html
{% load bootstrap5 %}
<head>
    {% load static %}
    <script type="text/javascript" src="{% static 'js/app.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/carousel.js' %}"></script>

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/schedules.css' %}">
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/lux/bootstrap.min.css"
          integrity="sha384-9+PGKSqjRdkeAU7Eu4nkJU8RFaH8ace8HGXnkiKMP9I9Te0GJ4/km3L1Z8tXigpG" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

run_stats/templates/run_stats/history.html
{% extends "run_stats/base.html" %}

{% block content %}
    <p>Hello, world!</p>
{% endblock content %}

run_stats/templates/run_stats/index.html
{% extends "run_stats/base.html" %}
{% load static %}

{% block header %}
    <h1>Welcome to stat-tracker.</h1>
    <div class="slide-wrapper">
        <ol class="slide-indexes">
            <a href="#slide-0">
                <button class="index-navigator"></button>
            </a>
            <a href="#slide-1">
                <button class="index-navigator"></button>
            </a>
            <a href="#slide-2">
                <button class="index-navigator"></button>
            </a>
        </ol>
        <div class="slides-container">
            <button class="carousel-button prev" onclick="scrollRight()">
                <span class="icon">
                <i class="bi bi-arrow-left"></i>
                </span>
            </button>
            <img id="slide-0" data-index="0" class="slide active" src="{% static 'images/running_man.jpeg' %}"
                 alt="gotta go fast">
            <img id="slide-1" data-index="1" class="slide" src="{% static 'images/marathon_image.jpeg' %}"
                 alt="run with friends">
            <img id="slide-2" data-index="2" class="slide" src="{% static 'images/running.jpeg' %}" alt="rin ran run">
            <button class="carousel-button next" onclick="navigateToRight()">
                <span class="icon">
                <i class="bi bi-arrow-right"></i>
                </span>
            </button>
        </div>
    </div>
{% endblock header %}

{% block content %}
    <p>Stat tracker helps you keep track of your running progress over time.</p>
{% endblock content %}

run_stats/templates/run_stats/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="/">stat-tracker</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'run_stats:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'run_stats:runs' %}">My runs</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'run_stats:history' %}">History</a>
            </li>
        </ul>

        <ul class="navbar-nav">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <p class="nav-link">Welcome, {{ user.username }}.</p>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                </li>

            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

run_stats/templates/run_stats/new_run.html
{% extends "run_stats/base.html" %}
{% load bootstrap5 %}
{% block content %}

    <h1 class="header">Add a new run:</h1>

    <form class="run-form" action="{% url 'run_stats:new_run' %}" method="post">
        {% csrf_token %}
        <div class="card border">
            {% bootstrap_form form %}
        </div>
        <div style="text-align: center">
            {% buttons submit='add run' %}{% endbuttons %}
        </div>
    </form>
{% endblock content %}

run_stats/templates/run_stats/run.html
{% extends "run_stats/base.html" %}

{% block content %}
    <p>Run {{ run }}</p>

    <p>You ran on {{ run.date|date:'Y M d' }} </p>

    <p>Splits:</p>
    <ul>
        {% for split in splits %}
            <li>
                {{ split.time|time:'i:s' }}
            </li>
        {% empty %}
            <p>No splits for run: {{ run }}</p>
        {% endfor %}
    </ul>
    <a href="{% url 'run_stats:add_splits' run.id %}">Add splits</a>

{% endblock content %}

run_stats/templates/run_stats/runs.html
{% extends "run_stats/base.html" %}

{% block content %}
    <p>Runs</p>

    <ul>
        {% for run in runs %}
            <li>
                <a href="{% url 'run_stats:run' run.id %}">{{ run.date }} - {{ run.distance }} miles
                    - {{ run.time|time:'H:i:s' }}</a> -
                <a href="{% url 'run_stats:edit_run' run.id %}"><i class="bi bi-pencil-square"></i>Edit run</a> -
                <a href="{% url 'run_stats:delete_run' run.id %}">Delete run</a>
            </li>

        {% empty %}
            <li>No runs have been added yet.</li>
        {% endfor %}

    </ul>

    <a href="{% url 'run_stats:new_run' %}">Add a new run:</a>

{% endblock content %}

run_stats/templates/schedule/schedule.html
{% extends "run_stats/base.html" %}
{% load bootstrap5 %}

{% block content %}

    <div>
        <p>Hello, world!</p>
    </div>

{% endblock content %}

run_stats/templates/schedule/schedules.html
{% extends "run_stats/base.html" %}
{% load bootstrap5 %}

{% block content %}

    <div class="schedule-container">
        {% for schedule in schedules %}
            <div class="schedule-card">

            <a href="{% url 'run_stats:get_schedule' schedule.id %}">{{ schedule }}</a>
            </div>
        {% endfor %}
    </div>

{% endblock content %}

users/templates/users/login.html
{% extends "run_stats/base.html" %}
{% load bootstrap5 %}

{% block content %}

    <div class="row justify-content-center">
        <div class="col-lg-8 col-md-10 col-sm-12">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">Log in</h3>
                    {% if form.errors %}
                        <p>Your username and password didn't match. Please try again.</p>
                    {% endif %}

                    <form method="POST" action="{% url 'users:login' %}">
                        {% csrf_token %}
                        {{ form.as_p }}

                        {% buttons submit='Log in' %} {% endbuttons %}

                        <input type="hidden" name="next" value="{% url 'run_stats:index' %}"/>

                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

users/templates/users/register.html
{% extends "run_stats/base.html" %}
{% load bootstrap5 %}

{% block content %}

    <div class="row justify-content-center">
        <div class="col-lg-8 col-md-10 col-sm-12">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">Sign up</h3>
                    <form method="POST" action="{% url 'users:register' %}">
                        {% csrf_token %}
                        {{ form.as_p }}

                        {% buttons submit='register' %} {% endbuttons %}

                        <input type="hidden" name="next" value="{% url 'run_stats:index' %}"/>

                    </form>
                </div>
                <div class="card-footer text-muted text-center">
                    Already have an account? <a href="{% url 'users:login' %}">Log in</a>
                </div>
            </div>
        </div>
    </div>



{% endblock content %}